flow_name = "架构理解"
flow_type = "SEQUENTIAL"
description =  '''

### 架构理解流程
该流程的目的是帮助架构师
1. 分析业务，理解项目的主要功能；
2. 提炼实现核心功能的主要类或者模块，分析类或模块之间的关系； 
3. 提炼实现核心业务的主要流程，及其涉及的相关内容。

'''

[[nodes]]
id = "node1"
name = "业务分析"
inputs = []
config = "node1_business_analysis.toml"

[[nodes]]
id = "node2"
name = "核心模块"
inputs = []
config = "node2_CoreModule.toml"

[[nodes]]
id = "node3"
name = "单核心类UML"
inputs = ["node2"]
config = "node3_SingleClassUML.toml"

[[nodes]]
id = "node4"
name = "多核心类UML"
inputs = ["node2"]
config = "node4_MultiClassUML.toml"

[[nodes]]
id = "node5"
name = "系统架构"
inputs = ["node1", "node3", "node4"]
config = "node5_SystemArchitect.toml"

