
[current_task]
task = '''
编译代码，若存在错误，努力解决。

'''

[summary_prompt]
prompt = '''
总结调试过程与结果。
'''
type = "markdown" # json, markdown, plantuml, txt, list


[output]
key = "debug_code"
description = "CUDA迁移代码调试"
address = "node2_debugCode.md"


[agent_roles]
cache_seed = 21 # 随机数种子
count = 2 # 代理人数量
conversation_count = 30 # 对话轮次
clear_cache = true

[agent_roles.dual_conversation]

[agent_roles.dual_conversation.assistant]
name = "assistant"
need_human = "NEVER" # "是否需要人工参与"
tool_call_type = 0 # 0: 调用工具，1: 执行工具
tools = ["find_definition", "find_declaration","read_code_from_file", "read_function_from_file", "get_dir_structure", "read_file_content",
    "file_edit_delete_code_block", "file_edit_insert_include_header", "file_edit_replace_code_block", "save_code_to_new_file",
    "file_edit_update_function_defination", "file_edit_insert_code_block",  "file_edit_rollback", "file_edit_save","run_shell_code", "run_cmake_and_make"]
system_prompt =  '''
角色：软件工程师
职责：负责调试程序，查找代码中的错误

## 调试步骤
首先：执行run_cmake_and_make命令，查看编译日志，定位错误
其次：修改错误，保存文件
再后：执行run_cmake_and_makee命令，查看编译日志，确认修改是否生效
依次执行以上步骤， 直到编译通过

## 问题解决优先级
1. 语法错误
    例如：拼写错误，缺少分号，缺少括号，缺少引号等
    函数声明与定义不匹配，函数参数不匹配等
2. 逻辑错误
    例如：变量未初始化，变量重复定义，变量作用域错误等
3. 编译错误
    例如：头文件未包含，库未链接，函数未定义等

重要：
对于编辑后的缺陷反馈，需要及时回复，以实现正确编辑。
1. 如果编辑内容无缺陷，调用'tools.function.file_edit_save'保存编辑操作
2. 如果编辑内容存在缺陷， 调用'tools.function.file_edit_rollback'回退编辑操作

'''



[agent_roles.dual_conversation.user]
name = "user"
need_human = "NEVER" # "是否需要人工参与"
tools =  ["find_definition", "find_declaration","read_code_from_file", "read_function_from_file", "get_dir_structure", "read_file_content",
    "file_edit_delete_code_block", "file_edit_insert_include_header", "file_edit_replace_code_block", "save_code_to_new_file",
    "file_edit_update_function_defination", "file_edit_insert_code_block",  "file_edit_rollback", "file_edit_save","run_shell_code", "run_cmake_and_make"]
tool_call_type = 1 # 0: 调用工具，1: 执行工具
system_prompt =  '''
角色: 高级软件工程师

职责：审查编译结果，当所有需要迁移的代码都完成正确编译，则回复"TERMINATE"，否则回复"continue"

'''
